Repository ITU-BDSA23-GROUP4/Chirp, pull requests merged in 2023-12, with the labels that each got.

#264 Removed scoped
  src/Chirp.Infrastructure/CheepRepository.cs
  src/Chirp.Razor/Program.cs
  test/Chirp.Infrastructure.Tests/CheepRepositoryCreateTest.cs
  test/Chirp.Infrastructure.Tests/CheepRepositoryUnitTests.cs
  test/Chirp.Infrastructure.Tests/InMemoryDatabaseUnitTest.cs
  test/Chirp.Infrastructure.Tests/RestrictedCheepsUnitTests.cs
Labels: enhancement

#280 Build test release and deployment
  Docs/BuildTestReleaseAndDeployment.md
  Docs/Images/ActivityDiagramProcess.drawio
  Docs/Images/ActivityDiagramProcess.png
  Docs/RunLocally.md
Labels: report

#286 Creation of AI Help Section
  Docs/Ai_help.md
Labels: report

#290 Adjust UML diagram
  Docs/Images/PackagesUMLClassDiagrams/PackageCoreUMLDiagram.drawio
  Docs/Images/PackagesUMLClassDiagrams/PackageCoreUMLDiagram.png
  Docs/Images/PackagesUMLClassDiagrams/PackageInfrastructureUMLDiagram.drawio
  Docs/Images/PackagesUMLClassDiagrams/PackageInfrastructureUMLDiagram.png
  Docs/Images/PackagesUMLClassDiagrams/PackagePagesUMLDiagram.drawio
  Docs/Images/PackagesUMLClassDiagrams/PackagePagesUMLDiagram.png
  src/Chirp.Core/CheepCreateDTO.cs
Labels: report

#291 Split activity diagram
  Docs/BuildTestReleaseAndDeployment.md
  Docs/Images/BuildAndDeploy.png
  Docs/Images/BuildAndTest.png
  Docs/Images/PublishNewRelease.png
Labels: enhancement, report

#304 Made extra test which required more test data
  test/Chirp.Infrastructure.Tests/CheepRepositoryUnitTests.cs
Labels: enhancement

#307 Made the activity diagrams the samll version
  docs/Report.md
Labels: enhancement
